#!/usr/bin/env bash
# Runs TPC-DS benchmark: generates tables and executes all 99 queries
# in a single spark-sql session to avoid Derby metastore persistence issues.
#
# Usage: run-tpcds-queries.sh <SPARK_HOME> <EVENT_LOG_DIR> <WAREHOUSE_DIR>
set -euo pipefail

SPARK_HOME="$1"
EVENT_LOG_DIR="$2"
WAREHOUSE_DIR="$3"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
QUERY_DIR="${SCRIPT_DIR}/queries"
COMBINED_SQL="/tmp/tpcds-combined.sql"

echo "=============================="
echo "TPC-DS Benchmark with DataFlint"
echo "=============================="
echo "Spark home: ${SPARK_HOME}"
echo "Event log dir: ${EVENT_LOG_DIR}"
echo "Warehouse dir: ${WAREHOUSE_DIR}"
echo ""

# Count total queries
TOTAL=$(ls "${QUERY_DIR}"/q*.sql 2>/dev/null | wc -l)
echo "Found ${TOTAL} TPC-DS queries to run"
echo ""

# Build a single combined SQL file: table creation + all queries
# Running in one spark-sql session avoids Derby metastore persistence issues
# (each separate spark-sql invocation cannot reliably access tables created
#  by a previous invocation due to Derby lock / catalog issues)
echo "Building combined SQL file..."
{
  echo "-- TPC-DS Combined: Table Creation + All Queries"
  echo "-- Generated by run-tpcds-queries.sh"
  echo ""

  # Table creation
  echo "-- =============================================="
  echo "-- PHASE 1: Create TPC-DS tables with synthetic data"
  echo "-- =============================================="
  cat "${SCRIPT_DIR}/create-tables.sql"
  echo ""
  echo ""

  # All queries
  echo "-- =============================================="
  echo "-- PHASE 2: Execute TPC-DS queries"
  echo "-- =============================================="
  for query_file in $(ls "${QUERY_DIR}"/q*.sql | sort -V); do
    query_name="$(basename "${query_file}" .sql)"
    echo ""
    echo "-- >>> ${query_name} <<<"
    cat "${query_file}"
    echo ";"
    echo ""
  done
} > "${COMBINED_SQL}"

LINE_COUNT=$(wc -l < "${COMBINED_SQL}")
echo "Combined SQL file: ${LINE_COUNT} lines"
echo ""

echo "--- Running all TPC-DS queries in a single Spark SQL session ---"
echo ""

# Run everything in one spark-sql session
if "${SPARK_HOME}/bin/spark-sql" \
  --master "local[*]" \
  --conf spark.plugins=io.dataflint.spark.SparkDataflintPlugin \
  --conf spark.dataflint.telemetry.enabled=false \
  --conf spark.eventLog.enabled=true \
  --conf "spark.eventLog.dir=file://${EVENT_LOG_DIR}" \
  --conf "spark.sql.warehouse.dir=${WAREHOUSE_DIR}" \
  --conf spark.driver.memory=2g \
  --conf spark.ui.enabled=false \
  --conf spark.sql.adaptive.enabled=true \
  --conf spark.sql.ansi.enabled=false \
  --conf "spark.app.name=TPC-DS-Benchmark" \
  -f "${COMBINED_SQL}" > /tmp/tpcds-run.out 2>&1; then
  echo "All queries completed successfully"
  EXIT_CODE=0
else
  EXIT_CODE=$?
  echo "spark-sql exited with code ${EXIT_CODE}"
fi

echo ""
echo "=============================="
echo "TPC-DS Execution Output (last 50 lines):"
echo "=============================="
tail -50 /tmp/tpcds-run.out 2>/dev/null || echo "(no output)"

# Check for errors in output
echo ""
echo "=============================="
echo "Error Analysis:"
echo "=============================="

ANALYSIS_ERRORS=$(grep -c "AnalysisException" /tmp/tpcds-run.out 2>/dev/null || echo "0")
PARSE_ERRORS=$(grep -c "ParseException" /tmp/tpcds-run.out 2>/dev/null || echo "0")
RUNTIME_ERRORS=$(grep -c "SparkException\|RuntimeException\|NullPointerException\|ClassNotFoundException" /tmp/tpcds-run.out 2>/dev/null || echo "0")

echo "  AnalysisException (missing table/column): ${ANALYSIS_ERRORS}"
echo "  ParseException (SQL syntax): ${PARSE_ERRORS}"
echo "  Runtime errors: ${RUNTIME_ERRORS}"

if [ "${ANALYSIS_ERRORS}" -gt 0 ] || [ "${PARSE_ERRORS}" -gt 0 ]; then
  echo ""
  echo "Unique SQL error messages:"
  grep -E "AnalysisException|ParseException" /tmp/tpcds-run.out 2>/dev/null | sort -u | head -30 | sed 's/^/  /'
fi

if [ "${RUNTIME_ERRORS}" -gt 0 ]; then
  echo ""
  echo "Runtime error messages:"
  grep -E "SparkException|RuntimeException|NullPointerException|ClassNotFoundException" /tmp/tpcds-run.out 2>/dev/null | sort -u | head -20 | sed 's/^/  /'
fi

# Only fail on runtime errors (possible plugin issues).
# Analysis/Parse errors are expected since some TPC-DS queries may use
# syntax not supported by a specific Spark version.
if [ "${RUNTIME_ERRORS}" -gt 0 ]; then
  echo ""
  echo "FAILED: Runtime errors detected (possible plugin issue)"
  exit 1
fi

if [ "${EXIT_CODE}" -ne 0 ] && [ "${ANALYSIS_ERRORS}" -eq 0 ] && [ "${PARSE_ERRORS}" -eq 0 ]; then
  echo ""
  echo "FAILED: Unknown error (exit code ${EXIT_CODE})"
  echo "Full output saved to /tmp/tpcds-run.out"
  exit 1
fi

echo ""
echo "=============================="
echo "PASSED (${ANALYSIS_ERRORS} analysis + ${PARSE_ERRORS} parse errors are expected Spark SQL limitations)"
echo "=============================="
